language: node_js
node_js:
  - "node"
before_script: npm test
script: npm run build:production
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    repo: rverbio/javascript-sdk
    node: 'node'
